package com.tangli.musicplayer.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tangli.musicplayer.bean.Coconut;

import com.tangli.musicplayer.database.greenDao.db.CoconutDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig coconutDaoConfig;

    private final CoconutDao coconutDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        coconutDaoConfig = daoConfigMap.get(CoconutDao.class).clone();
        coconutDaoConfig.initIdentityScope(type);

        coconutDao = new CoconutDao(coconutDaoConfig, this);

        registerDao(Coconut.class, coconutDao);
    }
    
    public void clear() {
        coconutDaoConfig.clearIdentityScope();
    }

    public CoconutDao getCoconutDao() {
        return coconutDao;
    }

}
